name: release

on:
  push:
    branches:
      - main
  repository_dispatch:
    types: [deploy]
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          persist-credentials: false

      - uses: 1024pix/pix-actions/release@main
        id: semantic
        with:
          changelogTitle: "# Pix data admin Changelog"
        env:
          GITHUB_TOKEN: ${{ secrets.PIX_SERVICE_RELEASE_ACTION_TOKEN }}
